EthernetServiceGroup support EthernetService support DomainName full support Network full support EpoServer support MgtServer full support LDAPServer support ActiveDirectoryServer full support ProxyServer full support SMTPServer support IcapServer support RadiusServer support TacacsServer support WebPortalServer support Enable Disable Api is not working in WebPortalAdminUser from smc-python. BGP full support(bgp_peering) virtual vlan interface to support on smc-python security alert digest on smc-python (cryptography) Initial contact engine: do not expect status when doing real initial contact AssertionError: Execution of python script alias.py has failed on API version 6.10: 55 != 0 STM is using cryptography lib version with CVEs Erreur:'ForcepointBGPElement' object has no attribute 'check_mode' readthedocs new configuration settings to apply alias resolve: resolved_value are missing